import { StatusData } from "./types"

export const TestData: StatusData = {
  framework: {
    name: "Karin",
    version: "v1.5.8",
    uptime: "12天 04:36:21",
    plugins: {
      total: 47,
      npm: 23,
      git: 18,
      app: 6,
    },
  },
  bots: [
    {
      id: "10086234567",
      nickname: "小喵酱",
      avatar: "/src/assets/image/logo.png",
      platform: "QQ",
      adapter: "Napcat",
      adapterVersion: "v1.2.0",
      sent: 12483000,
      received: 28991,
      friends: 156,
      groups: 42,
    },
    {
      id: "20088112233",
      nickname: "MochiBot",
      avatar: "/src/assets/image/logo.png",
      platform: "QQ",
      adapter: "OneBot",
      adapterVersion: "v11.4.2",
      sent: 8231,
      received: 19400,
      friends: 89,
      groups: 31,
    },
    {
      id: "telegram_neko",
      nickname: "TanukiSan",
      avatar: "/src/assets/image/logo.png",
      platform: "Telegram",
      adapter: "Telegraf",
      adapterVersion: "v4.16.3",
      sent: 3402,
      received: 7711,
      friends: 0,
      groups: 18,
    },
    {
      id: "kook_yume",
      nickname: "Yume夢",
      avatar: "/src/assets/image/logo.png",
      platform: "KOOK",
      adapter: "Kook-SDK",
      adapterVersion: "v0.9.1",
      sent: 1024,
      received: 3320,
      friends: 12,
      groups: 7,
    },
    {
      id: "discord_nyan",
      nickname: "NyanCore",
      avatar: "/src/assets/image/logo.png",
      platform: "Discord",
      adapter: "Discord.js",
      adapterVersion: "v14.15.0",
      sent: 5601,
      received: 12882,
      friends: 0,
      groups: 24,
    },
  ],
  cpu: {
    usage: 38,
    model: "AMD Ryzen 9 7950X3D",
    cores: 16,
    threads: 32,
    frequency: "4.2GHz",
  },
  mem: {
    ram: {
      used: 9.6,
      total: 32,
      free: 22.4,
      usage: 30,
    },
    swap: {
      used: 0.8,
      total: 8,
      free: 7.2,
      usage: 10,
    },
  },
  networks: [
    {
      name: "eth0",
      upSpeed: 1.24,
      downSpeed: 8.62,
      totalUp: 184.3,
      totalDown: 1.27,
    },
    {
      name: "wlan0",
      upSpeed: 0.12,
      downSpeed: 0.43,
      totalUp: 12.8,
      totalDown: 98.4,
    },
    {
      name: "tun0",
      upSpeed: 0.04,
      downSpeed: 0.21,
      totalUp: 3.2,
      totalDown: 11.6,
    }
  ],
  proc: {
    sort: "cpu",
    all: 256,
    running: 12,
    blocked: 5,
    sleeping: 230,
    unknown: 9,
    procs: [
      { name: "node (karin)", pid: 1984, cpu: 12.4, mem: 4.8 },
      { name: "node (napcat)", pid: 2031, cpu: 8.7, mem: 3.2 },
      { name: "redis-server", pid: 1102, cpu: 4.2, mem: 1.4 },
      { name: "mysqld", pid: 988, cpu: 3.8, mem: 6.1 },
      { name: "nginx", pid: 712, cpu: 1.6, mem: 0.4 },
      { name: "ffmpeg", pid: 4521, cpu: 22.1, mem: 2.3 },
      { name: "python3 (ml)", pid: 3344, cpu: 14.3, mem: 5.7 },
      { name: "chrome (puppeteer)", pid: 5012, cpu: 6.9, mem: 4.2 },
      { name: "systemd-journal", pid: 224, cpu: 0.4, mem: 0.3 },
      { name: "docker-proxy", pid: 1450, cpu: 0.8, mem: 0.6 },
    ]
  },
  hostInfo: {
    hostname: "neko-server-01",
    system: "Ubuntu 24.04 LTS",
    arch: "x86_64",
    kernel: "5.15.0-76-generic",
    timezone: "Asia/Shanghai (UTC+8)",
    uptime: "37天 18:42:09",
  },
  footer: "NekoStatus",
}